In [1]:
import pandas as pd

In [2]:
data= {
    'Name':['keerthana','sakthi','prabanchan','sajini','sandeep','kusum','dhanush','swetha','madhavan','aasha'],
    'Age':[21,22,20,21,23,22,20,20,20,19],
    'City':['cuddalore','bangalore','cuddalore','putlur','ambur','rajasthan','tirutani','tirutani','ariyalur','bangalore'],
    'gender':['female','male','male','female','male','female','male','female','male','female'],
    'qualification':['b.tech','b.tech','b.tech','b.tech','b.tech','b.tech','b.tech','b.tech','b.tech','b.tech'],
    'salary':[25000,30000,30000,40000,35000,40000,30000,50000,35000,25000]

}

In [10]:
df=pd.DataFrame(data)

In [14]:
df

         Name  Age       City  gender qualification  salary
0   keerthana   21  cuddalore  female        b.tech   25000
1      sakthi   22  bangalore    male        b.tech   30000
2  prabanchan   20  cuddalore    male        b.tech   30000
3      sajini   21     putlur  female        b.tech   40000
4     sandeep   23      ambur    male        b.tech   35000
5       kusum   22  rajasthan  female        b.tech   40000
6     dhanush   20   tirutani    male        b.tech   30000
7      swetha   20   tirutani  female        b.tech   50000
8    madhavan   20   ariyalur    male        b.tech   35000
9       aasha   19  bangalore  female        b.tech   25000

In [12]:
df.tail(4)

       Name  Age       City  gender qualification  salary
6   dhanush   20   tirutani    male        b.tech   30000
7    swetha   20   tirutani  female        b.tech   50000
8  madhavan   20   ariyalur    male        b.tech   35000
9     aasha   19  bangalore  female        b.tech   25000

In [15]:
df.head(3)

         Name  Age       City  gender qualification  salary
0   keerthana   21  cuddalore  female        b.tech   25000
1      sakthi   22  bangalore    male        b.tech   30000
2  prabanchan   20  cuddalore    male        b.tech   30000

In [17]:
df.shape

(10, 6)

In [18]:
df.size

60

In [20]:
df.columns

Index(['Name', 'Age', 'City', 'gender', 'qualification', 'salary'], dtype='object')

In [24]:
df.columns.values

array(['Name', 'Age', 'City', 'gender', 'qualification', 'salary'],
      dtype=object)

In [29]:
column_name=df.columns[2]

In [31]:
print(column_name)

City

In [41]:
res=sorted(df.columns)

In [42]:
print(res)

['Age', 'City', 'Name', 'gender', 'qualification', 'salary']

In [56]:
data=pd.read_csv('/student_performance.csv')

In [57]:
data

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade
0,1,John,Male,85,15,78,1,High,80
1,2,Sarah,Female,90,20,85,2,Medium,87
2,3,Alex,Male,78,10,65,0,Low,68
3,4,Michael,Male,92,25,90,3,High,92
4,5,Emma,Female,88,18,82,2,Medium,85
5,6,Olivia,Female,95,30,88,1,High,90
6,7,Daniel,Male,70,8,60,0,Low,62
7,8,Sophia,Female,85,17,77,1,Medium,78
8,9,James,Male,82,12,70,2,Low,72
9,10,Isabella,Female,91,22,86,3,High,88

In [59]:
data.head(3)

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade
0,1,John,Male,85,15,78,1,High,80
1,2,Sarah,Female,90,20,85,2,Medium,87
2,3,Alex,Male,78,10,65,0,Low,68

In [60]:
data.tail(2)

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade
8,9,James,Male,82,12,70,2,Low,72
9,10,Isabella,Female,91,22,86,3,High,88

In [63]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 9 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   StudentID                  10 non-null     int64
 1   Name                       10 non-null     object
 2   Gender                     10 non-null     object
 3   AttendanceRate             10 non-null     int64
 4   StudyHoursPerWeek          10 non-null     int64
 5   PreviousGrade              10 non-null     int64
 6   ExtracurricularActivities  10 non-null     int64
 7   ParentalSupport            10 non-null     object
 8   FinalGrade                 10 non-null     int64
dtypes: int64(6), object(3)
memory usage: 852.0+ bytes

In [64]:
data.shape

(10, 9)

In [65]:
data.size

90

In [66]:
data.AttendanceRate

0    85
1    90
2    78
3    92
4    88
5    95
6    70
7    85
8    82
9    91
Name: AttendanceRate, dtype: int64

In [67]:
data.columns

Index(['StudentID', 'Name', 'Gender', 'AttendanceRate', 'StudyHoursPerWeek',
       'PreviousGrade', 'ExtracurricularActivities', 'ParentalSupport',
       'FinalGrade'],
      dtype='object')

In [70]:
data.columns.values

array(['StudentID', 'Name', 'Gender', 'AttendanceRate',
       'StudyHoursPerWeek', 'PreviousGrade', 'ExtracurricularActivities',
       'ParentalSupport', 'FinalGrade'], dtype=object)

In [71]:
data.columns[5]

'PreviousGrade'

In [72]:
d=sorted(data.columns)

In [73]:
print(d)

['AttendanceRate', 'ExtracurricularActivities', 'FinalGrade', 'Gender', 'Name', 'ParentalSupport', 'PreviousGrade', 'StudentID', 'StudyHoursPerWeek']

In [75]:
data.describe()

,StudentID,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,FinalGrade
count,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000
mean,5.50000,85.600000,17.700000,78.100000,1.500000,80.200000
std,3.02765,7.441625,6.848357,10.170218,1.080123,10.097304
min,1.00000,70.000000,8.000000,60.000000,0.000000,62.000000
25%,3.25000,82.750000,12.750000,71.750000,1.000000,73.500000
50%,5.50000,86.500000,17.500000,80.000000,1.500000,82.500000
75%,7.75000,90.750000,21.500000,85.750000,2.000000,87.750000
max,10.00000,95.000000,30.000000,90.000000,3.000000,92.000000

In [80]:
data.isnull().sum()

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
dtype: int64

In [81]:
data=pd.read_csv('/student_performance.csv')

In [82]:
data

,StudentID,Name,Gender,AttendanceRate,StudyHoursPerWeek,PreviousGrade,ExtracurricularActivities,ParentalSupport,FinalGrade,Age
0,1,John,Male,85,15,78,1,High,80,23.0
1,2,Sarah,Female,90,20,85,2,Medium,87,33.0
2,3,Alex,Male,78,10,65,0,Low,68,56.0
3,4,Michael,Male,92,25,90,3,High,92,NaN
4,5,Emma,Female,88,18,82,2,Medium,85,67.0
5,6,Olivia,Female,95,30,88,1,High,90,78.0
6,7,Daniel,Male,70,8,60,0,Low,62,NaN
7,8,Sophia,Female,85,17,77,1,Medium,78,33.0
8,9,James,Male,82,12,70,2,Low,72,56.0
9,10,Isabella,Female,91,22,86,3,High,88,NaN

In [83]:
data.isnull().sum()

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Age                          3
dtype: int64

In [84]:
data.dropna(inplace=True)

In [85]:
data.isnull().sum()

StudentID                    0
Name                         0
Gender                       0
AttendanceRate               0
StudyHoursPerWeek            0
PreviousGrade                0
ExtracurricularActivities    0
ParentalSupport              0
FinalGrade                   0
Age                          0
dtype: int64